### ISSUE TITLE
Support for analyzing a specific git branch

### ISSUE THREAD

**Issue by gendx** [aschey/vercel-tokei#150]
Thank you for the great service, it's very reliable!

Something that seems to be missing here but is available on the original Tokei service is the ability to [count lines for a specific branch](https://github.com/XAMPPRocky/tokei_rs?tab=readme-ov-file#branch) on a git repository, rather than the default branch. Would you be open to add support for such a feature (`?branch=` parameter)?

**Comment by aschey** [comment]
Thanks for the heads up! This should be available now.
